services:
  influxdb2:
    image: 'influxdb:2'
    container_name: 'influxdb2'
    ports:
      - '8086:8086'
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: GatlingTest
      DOCKER_INFLUXDB_INIT_BUCKET: gatlingdb
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - 'influxdb2-data:/var/lib/influxdb2'
      - 'influxdb2-config:/etc/influxdb2'
      #      - './influxdb2/influxdb.conf:/var/lib/influxdb2'
    networks:
        - reseau

  telegraf:
    image: 'telegraf:latest'
    container_name: 'telegraf'
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on: 
      - influxdb2
    networks:
        - reseau

  gatling:
    image: 'maven:3.8.6-openjdk-11'
    container_name: 'gatling'
    entrypoint: /bin/bash
    command: -c "echo Running; cd /app/gatling; mvn gatling:test"
    volumes:
      - ~/Desktop/jenkins-gatling:/app/gatling
    depends_on:
      - influxdb2
      - telegraf

secrets:
  influxdb2-admin-username:
    file: './secrets/.env.influxdb2-admin-username'
  influxdb2-admin-password:
    file: './secrets/.env.influxdb2-admin-password'
  influxdb2-admin-token:
    file: './secrets/.env.influxdb2-admin-token'

volumes:
  influxdb2-data:
  influxdb2-config:

networks:
  reseau:
    driver: bridge
    name: reseau
